deployment:
  tasks:
    - source /home2/raynayx7/nodevenv/repositories/raynayxBlog/18/bin/activate && cd /home2/raynayx7/repositories/raynayxBlog
    - npx clean
    - npx hexo generate -d
    - git push origin
