theme_color:
  primary: "deep-purple 900" 
  accent: pink 

notice:

favicon: /images/favicon.ico
banner: /images/banner.png
avatar: /images/PASS_rene.jpg
# rss: /atom.xml

email: 
sns:
  twitter: https://twitter.com/RaynayX
  facebook:
  github: https://github.com/raynayx/ 
  linkedin:

open_graph:
  twitter:
  google_plus:
  fb_admins:
  fb_app_id:
site_verification:
  google:
  baidu:
analytics:
  google_site_id: G-1CPPFE4TBH

pages:
- name: test1 
  link: /tagcloud
- name: test2
  link: /gallery
links:
- name: morlantech
  link: https://morlantech.com
since:
footer_text:
license:

gallery:
  fancybox_css: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.css
  fancybox_js: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.js
  jquery_js: https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js
  lazyload_js: https://cdn.bootcss.com/jquery_lazyload/1.9.7/jquery.lazyload.min.js
busuanzi:
  site: false
  page: false
  busuanzi_js: http://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
qrcode:
  caption: send to phone
  use: online
donate:
search:
  placeholder: search 
  path: /search.xml
  use: online
comment:
  use: false
  disqus_shortname:
  gitalk_client_id:
  gitalk_client_secret:
  gitalk_repo:
  gitalk_owner:
  gitalk_sid_type:
  livere_data_uid:
  valine_leancloud_app_id:
  valine_leancloud_app_key:
  valine_placeholder:
  valine_page_size:
  valine_avatar:
  valine_lang:
  valine_guest_info:
  valine_notify:
  valine_verify:
  valine_sid_type:
  changyan_app_id:
  changyan_app_key:
  changyan_sid_type:
